### ISSUE TITLE
헤더 기능 붙히기

### ISSUE THREAD

**Issue by junghwa1996** [codeit-sprint-part2-2team/rolling#195]
## TODO
- [x] 받는 타입에 따라서 노출되는 스타일이 달라짐
- [x] 현재 url 가져와서 타입 조건 설정
- [x] 롤링배너의 경우 id값 받아서 상속 컴포넌트에 데이터 전달하기

**Comment by junghwa1996** [comment]
혹시 이거 언제쯤 완료될 수 있을지 알 수 있을까용?

**Comment by junghwa1996** [comment]
성우님~ 진행현황이 알고싶어용

**Comment by swp91** [comment]
앗 네 팀장님 확인이 늦어서 죄송합니다! 자정전후로 만들어보겠습니다
