### ISSUE TITLE
디자인 시스템 구축

### ISSUE THREAD

**Issue by junghwa1996** [codeit-sprint-part2-2team/rolling#221]
# 디자인 시스템
- 공통으로 사용되는 디자인 컴포넌트 문서
- 공통 컴포넌트 폴더 내에 `markdown` 문법을 사용하여, 문서 함께 작성
## 문서 작성법
1. 이 컴포넌트는 무엇인지(정의)
2. 무엇으로 구성되어 있는지
3. has Sub-category
4. Where use & Not use
6. state desc(ex: hover, click)
7. 디자인 스펙 설명

### TODO
- [x] 공통 스타일 속성 시트 제작
```javascript
// designSystem.styled.js
export const Title = styled.h2`
  ${({ $size }) => font[$size]};
  color: ${({ theme }) => theme.blackText};
`;

export const Desc = styled.p`
  ${({ $size }) => font[$size]}
  color: ${({ theme }) => theme.secondary};
`;
...
```
- [ ] 중복 UI/UX 별도 구분 (작성된 파일들 중)
- [ ] 공통 디자인 컴포넌트 제작 (확장성을 위한 세분화)

# 이슈 설명
## 이슈 생성
- 해당 관련 작업들은 이슈를 새로 생성하여, 작업하고 문서 규칙에 맞게 설명을 작성 합니다.
- 최상단에는 #221 을 작성하여, 해당 이슈의 하위 이슈임을 표기합니다.
- 마일스톤은 `버전 1.0.0 - 디자인 시스템` 으로 연결해주세요.
## PR
- 해당 디자인 시스템은 작업이 완료되면, `dev` 에 PR 요청을 하는 것이 아닌 **해당 `feature/#221 디자인 시스템 구축` 브랜치로 PR 요청해주세요**
## 하위 PR 연결
- `컴포넌트 이름` - #PR번호
- 하단에 추가해서 PR 연결해주세요.
---
- `Common.styled.js` - #226 
- `Button.jsx` - 
- `Badge.jsx` -

**Comment by junghwa1996** [comment]
추후 개발
