### ISSUE TITLE
스타일 초기화 세팅

### ISSUE THREAD

**Issue by junghwa1996** [codeit-sprint-part2-2team/rolling#52]
### 📝 TODO
- [x] reset.css 추가
- [x] normalize.css 추가
- [x] defult font import

### 상세내용
- 초기 스타일 전역으로 추가하기
